FROM python:3.12

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./auth /code/auth

CMD ["fastapi", "run", "auth/main.py", "--port", "80"]